### ISSUE TITLE
vty.c, buffer.c, command.c copyright statement likely wrong

### ISSUE THREAD

**Issue by laf0rge** [acassen/gtp-guard#31]
At first glance, the vty.c, buffer.c, command.c files appear to be derived from zebra/quagga (or any of its forks like libosmovty).  In that case, the copyright statement looks wrong.  The copyright statements of the original code should be preserved, together with the original license disclaimer.

**Comment by acassen** [comment]
yes, agreed... this is something kind of 'very very old' code, now FRR code is supporting more stuff around VTY... and I think there is a lot of differences now from this old version and the FRR one, but the goal here was just to request running daemon with something quite lite without the need to import third party lib. anyway you right will update Copyright.
